package com.gym.management.system.service;

import com.gym.management.system.dto.mapper.AttendanceDTOMapper;
import com.gym.management.system.dto.response.AttendanceResponseDTO;
import com.gym.management.system.entity.Attendance;
import com.gym.management.system.entity.Member;
import com.gym.management.system.exception.InvalidInputException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.AttendanceRepository;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.service.implementationclasses.AttendanceServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class AttendanceServiceImplTest {

    @Mock
    private AttendanceRepository attendanceRepository;

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private AttendanceDTOMapper attendanceDTOMapper;

    @InjectMocks
    private AttendanceServiceImpl attendanceService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Member member;
    private Attendance attendance;
    private AttendanceResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake member — id is auto-generated by DB, we just set it here to wire up relationships
        member = new Member();
        member.setMemberId(1L);

        // Fake attendance record — checked in but not yet checked out
        attendance = new Attendance();
        attendance.setMember(member);
        attendance.setDate(LocalDate.now());
        attendance.setCheckInTime(LocalTime.of(9, 0));
        attendance.setCheckOutTime(null); // not checked out yet

        // Fake response DTO returned by mapper
        responseDTO = new AttendanceResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // checkIn() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void checkIn_ShouldReturnResponse_WhenMemberHasNotCheckedInToday() {

        // Arrange — member exists, no check-in yet today
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(attendanceRepository.findByMemberMemberIdAndDate(1L, LocalDate.now()))
                .thenReturn(Optional.empty()); // no record for today
        when(attendanceRepository.save(any(Attendance.class))).thenReturn(attendance);
        when(attendanceDTOMapper.toResponse(attendance)).thenReturn(responseDTO);

        // Act
        AttendanceResponseDTO result = attendanceService.checkIn(1L);

        // Assert
        assertNotNull(result);
        verify(attendanceRepository).save(any(Attendance.class));
    }

    @Test
    void checkIn_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange — member not found in DB
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> attendanceService.checkIn(99L));
    }

    @Test
    void checkIn_ShouldThrowInvalidInputException_WhenMemberAlreadyCheckedInToday() {

        // Arrange — member exists and already has a check-in record for today
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(attendanceRepository.findByMemberMemberIdAndDate(1L, LocalDate.now()))
                .thenReturn(Optional.of(attendance)); // already checked in

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> attendanceService.checkIn(1L));
    }

    // ════════════════════════════════════════════════════════════
    // checkOut() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void checkOut_ShouldReturnResponse_WhenMemberHasCheckedInAndNotYetCheckedOut() {

        // Arrange — member exists, has checked in, checkout time is null
        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberIdAndDate(1L, LocalDate.now()))
                .thenReturn(Optional.of(attendance)); // attendance exists, checkOutTime is null
        when(attendanceRepository.save(any(Attendance.class))).thenReturn(attendance);
        when(attendanceDTOMapper.toResponse(attendance)).thenReturn(responseDTO);

        // Act
        AttendanceResponseDTO result = attendanceService.checkOut(1L);

        // Assert
        assertNotNull(result);
        verify(attendanceRepository).save(any(Attendance.class));
    }

    @Test
    void checkOut_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange — member not in DB
        when(memberRepository.existsById(99L)).thenReturn(false);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> attendanceService.checkOut(99L));
    }

    @Test
    void checkOut_ShouldThrowNotFoundException_WhenMemberHasNotCheckedInToday() {

        // Arrange — member exists but no attendance record found for today
        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberIdAndDate(1L, LocalDate.now()))
                .thenReturn(Optional.empty()); // no check-in record

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> attendanceService.checkOut(1L));
    }

    @Test
    void checkOut_ShouldThrowInvalidInputException_WhenMemberAlreadyCheckedOut() {

        // Arrange — member already has a check-out time set
        attendance.setCheckOutTime(LocalTime.of(17, 0)); // already checked out
        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberIdAndDate(1L, LocalDate.now()))
                .thenReturn(Optional.of(attendance));

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> attendanceService.checkOut(1L));
    }

    // ════════════════════════════════════════════════════════════
    // getAttendanceByMember() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAttendanceByMember_ShouldReturnList_WhenMemberExists() {

        // Arrange
        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberId(1L)).thenReturn(List.of(attendance));
        when(attendanceDTOMapper.toResponse(List.of(attendance))).thenReturn(List.of(responseDTO));

        // Act
        List<AttendanceResponseDTO> result = attendanceService.getAttendanceByMember(1L);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getAttendanceByMember_ShouldReturnEmptyList_WhenMemberHasNoAttendance() {

        // Arrange — member exists but has no attendance records
        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberId(1L)).thenReturn(List.of());
        when(attendanceDTOMapper.toResponse(List.of())).thenReturn(List.of());

        // Act
        List<AttendanceResponseDTO> result = attendanceService.getAttendanceByMember(1L);

        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    @Test
    void getAttendanceByMember_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.existsById(99L)).thenReturn(false);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> attendanceService.getAttendanceByMember(99L));
    }

    // ════════════════════════════════════════════════════════════
    // getTodayAttendance() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getTodayAttendance_ShouldReturnList_WhenAttendanceRecordsExistForToday() {

        // Arrange
        when(attendanceRepository.findByDate(LocalDate.now())).thenReturn(List.of(attendance));
        when(attendanceDTOMapper.toResponse(List.of(attendance))).thenReturn(List.of(responseDTO));

        // Act
        List<AttendanceResponseDTO> result = attendanceService.getTodayAttendance();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getTodayAttendance_ShouldReturnEmptyList_WhenNoOneCheckedInToday() {

        // Arrange — nobody checked in today
        when(attendanceRepository.findByDate(LocalDate.now())).thenReturn(List.of());
        when(attendanceDTOMapper.toResponse(List.of())).thenReturn(List.of());

        // Act
        List<AttendanceResponseDTO> result = attendanceService.getTodayAttendance();

        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    // ════════════════════════════════════════════════════════════
    // getAttendanceByMemberAndDateRange() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAttendanceByMemberAndDateRange_ShouldReturnList_WhenValidRangeProvided() {

        // Arrange
        LocalDate startDate = LocalDate.now().minusDays(7);
        LocalDate endDate = LocalDate.now();

        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberIdAndDateBetween(1L, startDate, endDate))
                .thenReturn(List.of(attendance));
        when(attendanceDTOMapper.toResponse(List.of(attendance))).thenReturn(List.of(responseDTO));

        // Act
        List<AttendanceResponseDTO> result =
                attendanceService.getAttendanceByMemberAndDateRange(1L, startDate, endDate);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getAttendanceByMemberAndDateRange_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.existsById(99L)).thenReturn(false);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> attendanceService.getAttendanceByMemberAndDateRange(
                        99L, LocalDate.now().minusDays(7), LocalDate.now()));
    }

    @Test
    void getAttendanceByMemberAndDateRange_ShouldThrowInvalidInputException_WhenStartDateIsAfterEndDate() {

        // Arrange — invalid range: start is after end
        LocalDate startDate = LocalDate.now();
        LocalDate endDate = LocalDate.now().minusDays(5); // end before start

        when(memberRepository.existsById(1L)).thenReturn(true);

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> attendanceService.getAttendanceByMemberAndDateRange(1L, startDate, endDate));
    }

    @Test
    void getAttendanceByMemberAndDateRange_ShouldReturnEmptyList_WhenNoAttendanceInRange() {

        // Arrange — valid range but no records found
        LocalDate startDate = LocalDate.now().minusDays(30);
        LocalDate endDate = LocalDate.now().minusDays(20);

        when(memberRepository.existsById(1L)).thenReturn(true);
        when(attendanceRepository.findByMemberMemberIdAndDateBetween(1L, startDate, endDate))
                .thenReturn(List.of());
        when(attendanceDTOMapper.toResponse(List.of())).thenReturn(List.of());

        // Act
        List<AttendanceResponseDTO> result =
                attendanceService.getAttendanceByMemberAndDateRange(1L, startDate, endDate);

        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }

}