package com.gym.management.system.service;

import com.gym.management.system.dto.mapper.AttendanceDTOMapper;
import com.gym.management.system.dto.response.AttendanceResponseDTO;
import com.gym.management.system.entity.Attendance;
import com.gym.management.system.entity.Member;
import com.gym.management.system.exception.InvalidInputException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.AttendanceRepository;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.service.implementationclasses.AttendanceServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class AttendanceServiceImplTest {

    @Mock
    private AttendanceRepository attendanceRepository;

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private AttendanceDTOMapper attendanceDTOMapper;

    @InjectMocks
    private AttendanceServiceImpl attendanceService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Member member;
    private Attendance attendance;
    private AttendanceResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake member — id is auto-generated by DB, we just set it here to wire up relationships
        member = new Member();
        member.setMemberId(1L);

        // Fake attendance record — checked in but not yet checked out
        attendance = new Attendance();
        attendance.setMember(member);
        attendance.setDate(LocalDate.now());
        attendance.setCheckInTime(LocalTime.of(9, 0));
        attendance.setCheckOutTime(null); // not checked out yet

        // Fake response DTO returned by mapper
        responseDTO = new AttendanceResponseDTO();
    }
}