package com.gym.management.system.service;


import com.gym.management.system.dto.request.AuthRequestDTO;
import com.gym.management.system.dto.request.ChangePasswordRequestDTO;
import com.gym.management.system.dto.response.AuthResponseDTO;
import com.gym.management.system.entity.RefreshToken;
import com.gym.management.system.entity.User;
import com.gym.management.system.enums.UserRoles;
import com.gym.management.system.exception.InvalidInputException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.exception.TokenException;
import com.gym.management.system.repository.RefreshTokenRepository;
import com.gym.management.system.repository.UserRepository;
import com.gym.management.system.security.JwtUtil;
import com.gym.management.system.service.implementationclasses.AuthServiceImpl;
import com.gym.management.system.service.interfaces.RefreshTokenService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)

public class AuthServiceImplTest {

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private JwtUtil jwtUtil;

    @Mock
    private UserRepository userRepository;

    @Mock
    private RefreshTokenService refreshTokenService;

    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private AuthServiceImpl authService;

    // ─── Shared test data ────────────────────────────────────────────────

    private User user;
    private RefreshToken refreshToken;

    @BeforeEach
    void setUp() {

        // Fake user — id is auto-generated by DB, set here just to wire up relationships
        user = new User();
        user.setUsername("john_doe");
        user.setPassword("encodedPassword");
        user.setUserRole(UserRoles.MEMBER);

        // Fake refresh token linked to user
        refreshToken = new RefreshToken();
        refreshToken.setToken("fake-refresh-token");
        refreshToken.setUser(user);
    }

    // ════════════════════════════════════════════════════════════
    // login() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void login_ShouldReturnAuthResponse_WhenCredentialsAreValid() {

        // Arrange — authentication passes, user found, tokens generated
        AuthRequestDTO request = new AuthRequestDTO();
        request.setUsername("john_doe");
        request.setPassword("rawPassword");

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));
        when(jwtUtil.generateToken("john_doe", "MEMBER")).thenReturn("fake-access-token");
        when(refreshTokenService.createRefreshToken(user)).thenReturn(refreshToken);

        // Act
        AuthResponseDTO result = authService.login(request);

        // Assert — both tokens should be present in response
        assertNotNull(result);
        assertEquals("fake-access-token", result.getAccessToken());
        assertEquals("fake-refresh-token", result.getRefreshToken());

        // Verify old refresh token was deleted before creating new one
        verify(refreshTokenRepository).deleteByUser(user);
        verify(refreshTokenService).createRefreshToken(user);
    }

    @Test
    void login_ShouldThrowException_WhenCredentialsAreInvalid() {

        // Arrange — authentication manager throws exception for bad credentials
        AuthRequestDTO request = new AuthRequestDTO();
        request.setUsername("john_doe");
        request.setPassword("wrongPassword");

        doThrow(new BadCredentialsException("Bad credentials"))
                .when(authenticationManager)
                .authenticate(any(UsernamePasswordAuthenticationToken.class));

        // Act & Assert
        assertThrows(BadCredentialsException.class,
                () -> authService.login(request));

        // Verify no tokens were created since auth failed
        verifyNoInteractions(userRepository, refreshTokenService, jwtUtil);
    }

    @Test
    void login_ShouldThrowTokenException_WhenUserNotFoundAfterAuthentication() {

        // Arrange — auth passes but user somehow not found in DB
        AuthRequestDTO request = new AuthRequestDTO();
        request.setUsername("john_doe");
        request.setPassword("rawPassword");

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(TokenException.class,
                () -> authService.login(request));
    }

    // ════════════════════════════════════════════════════════════
    // refreshToken() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void refreshToken_ShouldReturnNewTokens_WhenRefreshTokenIsValid() {

        // Arrange — old token is valid, new tokens are generated
        RefreshToken newRefreshToken = new RefreshToken();
        newRefreshToken.setToken("new-refresh-token");
        newRefreshToken.setUser(user);

        when(refreshTokenService.verifyRefreshToken("fake-refresh-token")).thenReturn(refreshToken);
        when(refreshTokenService.createRefreshToken(user)).thenReturn(newRefreshToken);
        when(jwtUtil.generateToken("john_doe", "MEMBER")).thenReturn("new-access-token");

        // Act
        AuthResponseDTO result = authService.refreshToken("fake-refresh-token");

        // Assert — new tokens returned
        assertNotNull(result);
        assertEquals("new-access-token", result.getAccessToken());
        assertEquals("new-refresh-token", result.getRefreshToken());

        // Verify old token was deleted
        verify(refreshTokenRepository).delete(refreshToken);
    }

    @Test
    void refreshToken_ShouldThrowException_WhenRefreshTokenIsInvalid() {

        // Arrange — token verification fails (expired or not found)
        when(refreshTokenService.verifyRefreshToken("invalid-token"))
                .thenThrow(new TokenException("Refresh token is invalid or expired"));

        // Act & Assert
        assertThrows(TokenException.class,
                () -> authService.refreshToken("invalid-token"));

        // Verify no new tokens were created
        verify(refreshTokenRepository, never()).delete(any());
        verify(refreshTokenService, never()).createRefreshToken(any());
    }

    // ════════════════════════════════════════════════════════════
    // logout() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void logout_ShouldDeleteRefreshToken_WhenCalled() {

        // Act — logout with a token
        authService.logout("fake-refresh-token");

        // Assert — token should be deleted from DB
        verify(refreshTokenRepository).deleteByToken("fake-refresh-token");
    }

    // ════════════════════════════════════════════════════════════
    // changePassword() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void changePassword_ShouldSaveNewPassword_WhenAllValidationsPass() {

        // Arrange — current password matches, new passwords match, new != current
        ChangePasswordRequestDTO dto = new ChangePasswordRequestDTO();
        dto.setCurrentPassword("currentRaw");
        dto.setNewPassword("newRaw");
        dto.setConfirmPassword("newRaw");

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));
        when(passwordEncoder.matches("currentRaw", "encodedPassword")).thenReturn(true);  // current password correct
        when(passwordEncoder.matches("newRaw", "encodedPassword")).thenReturn(false);     // new != current
        when(passwordEncoder.encode("newRaw")).thenReturn("newEncodedPassword");

        // Act
        authService.changePassword("john_doe", dto);

        // Assert — new encoded password saved
        verify(userRepository).save(user);
        assertEquals("newEncodedPassword", user.getPassword());
    }

    @Test
    void changePassword_ShouldThrowNotFoundException_WhenUserNotFound() {

        // Arrange — no user linked to this username
        ChangePasswordRequestDTO dto = new ChangePasswordRequestDTO();

        when(userRepository.findByUsername("unknown")).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> authService.changePassword("unknown", dto));
    }

    @Test
    void changePassword_ShouldThrowInvalidInputException_WhenCurrentPasswordIsWrong() {

        // Arrange — current password does not match stored password
        ChangePasswordRequestDTO dto = new ChangePasswordRequestDTO();
        dto.setCurrentPassword("wrongCurrent");
        dto.setNewPassword("newRaw");
        dto.setConfirmPassword("newRaw");

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));
        when(passwordEncoder.matches("wrongCurrent", "encodedPassword")).thenReturn(false); // wrong password

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> authService.changePassword("john_doe", dto));
    }

    @Test
    void changePassword_ShouldThrowInvalidInputException_WhenNewPasswordAndConfirmPasswordDoNotMatch() {

        // Arrange — new password and confirm password are different
        ChangePasswordRequestDTO dto = new ChangePasswordRequestDTO();
        dto.setCurrentPassword("currentRaw");
        dto.setNewPassword("newRaw");
        dto.setConfirmPassword("differentRaw"); // mismatch

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));
        when(passwordEncoder.matches("currentRaw", "encodedPassword")).thenReturn(true); // current password correct

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> authService.changePassword("john_doe", dto));
    }

    @Test
    void changePassword_ShouldThrowInvalidInputException_WhenNewPasswordIsSameAsCurrentPassword() {

        // Arrange — new password is the same as current password
        ChangePasswordRequestDTO dto = new ChangePasswordRequestDTO();
        dto.setCurrentPassword("currentRaw");
        dto.setNewPassword("currentRaw");   // same as current
        dto.setConfirmPassword("currentRaw");

        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));
        when(passwordEncoder.matches("currentRaw", "encodedPassword")).thenReturn(true); // current password correct
        when(passwordEncoder.matches("currentRaw", "encodedPassword")).thenReturn(true); // new == current

        // Act & Assert
        assertThrows(InvalidInputException.class,
                () -> authService.changePassword("john_doe", dto));
    }
}
