package com.gym.management.system.service;


import com.gym.management.system.dto.request.AuthRequestDTO;
import com.gym.management.system.dto.request.ChangePasswordRequestDTO;
import com.gym.management.system.dto.response.AuthResponseDTO;
import com.gym.management.system.entity.RefreshToken;
import com.gym.management.system.entity.User;
import com.gym.management.system.enums.UserRoles;
import com.gym.management.system.exception.InvalidInputException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.exception.TokenException;
import com.gym.management.system.repository.RefreshTokenRepository;
import com.gym.management.system.repository.UserRepository;
import com.gym.management.system.security.JwtUtil;
import com.gym.management.system.service.implementationclasses.AuthServiceImpl;
import com.gym.management.system.service.interfaces.RefreshTokenService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)

public class AuthServiceImplTest {

    @Mock
    private AuthenticationManager authenticationManager;

    @Mock
    private JwtUtil jwtUtil;

    @Mock
    private UserRepository userRepository;

    @Mock
    private RefreshTokenService refreshTokenService;

    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private AuthServiceImpl authService;

    // ─── Shared test data ────────────────────────────────────────────────

    private User user;
    private RefreshToken refreshToken;

    @BeforeEach
    void setUp() {

        // Fake user — id is auto-generated by DB, set here just to wire up relationships
        user = new User();
        user.setUsername("john_doe");
        user.setPassword("encodedPassword");
        user.setUserRole(UserRoles.MEMBER);

        // Fake refresh token linked to user
        refreshToken = new RefreshToken();
        refreshToken.setToken("fake-refresh-token");
        refreshToken.setUser(user);
    }

}
