package com.gym.management.system.service;

import com.gym.management.system.entity.User;
import com.gym.management.system.enums.UserRoles;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.UserRepository;
import com.gym.management.system.service.implementationclasses.CustomUserDetailsService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.userdetails.UserDetails;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CustomUserDetailsServiceTest {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private CustomUserDetailsService customUserDetailsService;

    // ─── Shared test data ────────────────────────────────────────────────

    private User user;

    @BeforeEach
    void setUp() {

        // Fake user — id is auto-generated by DB, set here just to wire up relationships
        user = new User();
        user.setUsername("john_doe");
        user.setPassword("encodedPassword");
        user.setUserRole(UserRoles.MEMBER);
    }

    // ════════════════════════════════════════════════════════════
    // loadUserByUsername() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void loadUserByUsername_ShouldReturnUserDetails_WhenUserExists() {

        // Arrange — user found in DB
        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));

        // Act
        UserDetails result = customUserDetailsService.loadUserByUsername("john_doe");

        // Assert — returned UserDetails should match the user entity
        assertNotNull(result);
        assertEquals("john_doe", result.getUsername());
        assertEquals("encodedPassword", result.getPassword());
    }

    @Test
    void loadUserByUsername_ShouldHaveCorrectRole_WhenUserExists() {

        // Arrange
        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));

        // Act
        UserDetails result = customUserDetailsService.loadUserByUsername("john_doe");

        // Assert — Spring Security prefixes roles with "ROLE_" internally
        assertNotNull(result);
        assertTrue(result.getAuthorities().stream()
                .anyMatch(auth -> auth.getAuthority().equals("ROLE_MEMBER")));
    }

    @Test
    void loadUserByUsername_ShouldThrowNotFoundException_WhenUserDoesNotExist() {

        // Arrange — no user found for this username
        when(userRepository.findByUsername("unknown")).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> customUserDetailsService.loadUserByUsername("unknown"));
    }

    @Test
    void loadUserByUsername_ShouldReturnCorrectRole_WhenUserIsAdmin() {

        // Arrange — admin user
        user.setUserRole(UserRoles.ADMIN);
        when(userRepository.findByUsername("john_doe")).thenReturn(Optional.of(user));

        // Act
        UserDetails result = customUserDetailsService.loadUserByUsername("john_doe");

        // Assert — role should be ADMIN
        assertNotNull(result);
        assertTrue(result.getAuthorities().stream()
                .anyMatch(auth -> auth.getAuthority().equals("ROLE_ADMIN")));
    }
}