package com.gym.management.system.service;

import com.gym.management.system.dto.mapper.MembershipPlanDTOMapper;
import com.gym.management.system.dto.request.MembershipPlanRequestDTO;
import com.gym.management.system.dto.response.MembershipPlanResponseDTO;
import com.gym.management.system.entity.MembershipPlan;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.MembershipPlanRepository;
import com.gym.management.system.service.implementationclasses.MembershipPlanServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class MembershipPlanServiceImplTest {


    @Mock
    private MembershipPlanRepository membershipPlanRepository;

    @Mock
    private MembershipPlanDTOMapper membershipPlanDTOMapper;

    @InjectMocks
    private MembershipPlanServiceImpl membershipPlanService;

    // ─── Shared test data ────────────────────────────────────────────────

    private MembershipPlan plan;
    private MembershipPlanRequestDTO requestDTO;
    private MembershipPlanResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake plan — id is auto-generated by DB, set here just to wire up relationships
        plan = new MembershipPlan();
        plan.setName("Gold Plan");
        plan.setDescription("Premium access");
        plan.setDurationDays(30);
        plan.setPrice(999.0);
        plan.setActive(true);

        // Fake request DTO — what admin sends when creating/updating a plan
        requestDTO = new MembershipPlanRequestDTO();
        requestDTO.setName("Gold Plan");
        requestDTO.setDescription("Premium access");
        requestDTO.setDurationDays(30);
        requestDTO.setPrice(999.0);

        // Fake response DTO returned after mapping
        responseDTO = new MembershipPlanResponseDTO();
    }
}
