package com.gym.management.system.service;

import com.gym.management.system.dto.mapper.MembershipPlanDTOMapper;
import com.gym.management.system.dto.request.MembershipPlanRequestDTO;
import com.gym.management.system.dto.response.MembershipPlanResponseDTO;
import com.gym.management.system.entity.MembershipPlan;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.MembershipPlanRepository;
import com.gym.management.system.service.implementationclasses.MembershipPlanServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class MembershipPlanServiceImplTest {


    @Mock
    private MembershipPlanRepository membershipPlanRepository;

    @Mock
    private MembershipPlanDTOMapper membershipPlanDTOMapper;

    @InjectMocks
    private MembershipPlanServiceImpl membershipPlanService;

    // ─── Shared test data ────────────────────────────────────────────────

    private MembershipPlan plan;
    private MembershipPlanRequestDTO requestDTO;
    private MembershipPlanResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake plan — id is auto-generated by DB, set here just to wire up relationships
        plan = new MembershipPlan();
        plan.setName("Gold Plan");
        plan.setDescription("Premium access");
        plan.setDurationDays(30);
        plan.setPrice(999.0);
        plan.setActive(true);

        // Fake request DTO — what admin sends when creating/updating a plan
        requestDTO = new MembershipPlanRequestDTO();
        requestDTO.setName("Gold Plan");
        requestDTO.setDescription("Premium access");
        requestDTO.setDurationDays(30);
        requestDTO.setPrice(999.0);

        // Fake response DTO returned after mapping
        responseDTO = new MembershipPlanResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // createPlan() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void createPlan_ShouldReturnResponse_WhenPlanNameIsUnique() {

        // Arrange — plan name does not exist yet
        when(membershipPlanRepository.existsByName("Gold Plan")).thenReturn(false);
        when(membershipPlanDTOMapper.toEntity(requestDTO)).thenReturn(plan);
        when(membershipPlanRepository.save(plan)).thenReturn(plan);
        when(membershipPlanDTOMapper.toResponse(plan)).thenReturn(responseDTO);

        // Act
        MembershipPlanResponseDTO result = membershipPlanService.createPlan(requestDTO);

        // Assert
        assertNotNull(result);
        verify(membershipPlanRepository).save(plan);
    }

    @Test
    void createPlan_ShouldSetActiveToTrue_WhenPlanIsCreated() {

        // Arrange — plan starts as inactive to verify service sets it to true
        plan.setActive(false);

        when(membershipPlanRepository.existsByName("Gold Plan")).thenReturn(false);
        when(membershipPlanDTOMapper.toEntity(requestDTO)).thenReturn(plan);
        when(membershipPlanRepository.save(plan)).thenReturn(plan);
        when(membershipPlanDTOMapper.toResponse(plan)).thenReturn(responseDTO);

        // Act
        membershipPlanService.createPlan(requestDTO);

        // Assert — service should always set active=true on creation
        assertTrue(plan.isActive());
    }

    @Test
    void createPlan_ShouldThrowAlreadyPresentException_WhenPlanNameAlreadyExists() {

        // Arrange — plan name is already taken
        when(membershipPlanRepository.existsByName("Gold Plan")).thenReturn(true);

        // Act & Assert
        assertThrows(AlreadyPresentException.class,
                () -> membershipPlanService.createPlan(requestDTO));

        // Verify no plan was saved
        verify(membershipPlanRepository, never()).save(any());
    }

}
