package com.gym.management.system.service;


import com.gym.management.system.dto.mapper.MemberDTOMapper;
import com.gym.management.system.dto.request.MemberRequestDTO;
import com.gym.management.system.dto.response.MemberResponseDTO;
import com.gym.management.system.entity.Member;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.User;
import com.gym.management.system.enums.MemberStatus;
import com.gym.management.system.enums.UserRoles;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.exception.TokenException;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.repository.TrainerRepository;
import com.gym.management.system.repository.UserRepository;
import com.gym.management.system.security.SecurityUtils;
import com.gym.management.system.service.implementationclasses.MemberServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class MemberServiceImplTest {

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private UserRepository userRepository;

    @Mock
    private MemberDTOMapper memberDtoMapper;

    @Mock
    private SecurityUtils securityUtils;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private MemberServiceImpl memberService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Member member;
    private Trainer trainer;
    private MemberRequestDTO requestDTO;
    private MemberResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Inject @Value field since Spring doesn't run in unit tests
        ReflectionTestUtils.setField(memberService, "defaultMemberPassword", "Gym@123");

        // Fake member — id is auto-generated by DB, set here just to wire up relationships
        member = new Member();
        member.setMemberId(1L);
        member.setPhoneNumber("9876543210");
        member.setMemberName("John Doe");
        member.setStatus(MemberStatus.ACTIVE);

        // Fake trainer
        trainer = new Trainer();
        trainer.setTrainerId(10L);

        // Fake request DTO — what admin sends when creating/updating a member
        requestDTO = new MemberRequestDTO();
        requestDTO.setMemberName("John Doe");
        requestDTO.setPhoneNumber("9876543210");

        // Fake response DTO returned after mapping
        responseDTO = new MemberResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // getAllMembers() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAllMembers_ShouldReturnPagedResult_WhenMembersExist() {

        // Arrange
        Page<Member> memberPage = new PageImpl<>(List.of(member));
        when(memberRepository.findAll(any(PageRequest.class))).thenReturn(memberPage);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        Page<MemberResponseDTO> result = memberService.getAllMembers(0, 10, "memberName", "asc");

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getTotalElements());
    }

    @Test
    void getAllMembers_ShouldReturnEmptyPage_WhenNoMembersExist() {

        // Arrange — no members in DB yet
        when(memberRepository.findAll(any(PageRequest.class))).thenReturn(Page.empty());

        // Act
        Page<MemberResponseDTO> result = memberService.getAllMembers(0, 10, "memberName", "asc");

        // Assert — empty page is valid, not an error
        assertNotNull(result);
        assertEquals(0, result.getTotalElements());
    }

    // ════════════════════════════════════════════════════════════
    // getMemberById() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getMemberById_ShouldReturnResponse_WhenMemberExists() {

        // Arrange
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        MemberResponseDTO result = memberService.getMemberById(1L);

        // Assert
        assertNotNull(result);
    }

    @Test
    void getMemberById_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.getMemberById(99L));
    }

    // ════════════════════════════════════════════════════════════
    // addMember() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void addMember_ShouldReturnResponse_WhenPhoneNumberIsNotAlreadyRegistered() {

        // Arrange — phone number is unique, user and member created successfully
        when(memberRepository.existsByPhoneNumber("9876543210")).thenReturn(false);
        when(passwordEncoder.encode("Gym@123")).thenReturn("encodedPassword");
        when(userRepository.save(any(User.class))).thenReturn(new User());
        when(memberDtoMapper.toEntity(requestDTO)).thenReturn(member);
        when(memberRepository.save(any(Member.class))).thenReturn(member);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        MemberResponseDTO result = memberService.addMember(requestDTO);

        // Assert
        assertNotNull(result);

        // Verify a user account was also created for this member
        verify(userRepository).save(any(User.class));
        verify(memberRepository).save(any(Member.class));
    }

    @Test
    void addMember_ShouldThrowAlreadyPresentException_WhenPhoneNumberAlreadyRegistered() {

        // Arrange — phone number already exists in DB
        when(memberRepository.existsByPhoneNumber("9876543210")).thenReturn(true);

        // Act & Assert
        assertThrows(AlreadyPresentException.class,
                () -> memberService.addMember(requestDTO));

        // Verify no user or member was created
        verifyNoInteractions(userRepository);
        verify(memberRepository, never()).save(any());
    }


    // ════════════════════════════════════════════════════════════
    // updateMember() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void updateMember_ShouldReturnUpdatedResponse_WhenMemberExists() {

        // Arrange
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(memberRepository.save(member)).thenReturn(member);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        MemberResponseDTO result = memberService.updateMember(1L, requestDTO);

        // Assert
        assertNotNull(result);
        verify(memberRepository).save(member);
    }

    @Test
    void updateMember_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.updateMember(99L, requestDTO));
    }

    // ════════════════════════════════════════════════════════════
    // deleteMember() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void deleteMember_ShouldDeleteMemberAndLinkedUser_WhenMemberExists() {

        // Arrange — member has a linked user account
        User linkedUser = new User();
        member.setUser(linkedUser);

        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));

        // Act
        memberService.deleteMember(1L);

        // Assert — both member and user should be deleted
        verify(userRepository).delete(linkedUser);
        verify(memberRepository).delete(member);
    }

    @Test
    void deleteMember_ShouldDeleteMemberOnly_WhenNoLinkedUserExists() {

        // Arrange — member has no linked user account
        member.setUser(null);
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));

        // Act
        memberService.deleteMember(1L);

        // Assert — only member deleted, no user deletion attempted
        verify(userRepository, never()).delete(any());
        verify(memberRepository).delete(member);
    }

    @Test
    void deleteMember_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.deleteMember(99L));
    }

    // ════════════════════════════════════════════════════════════
    // updateMemberStatus() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void updateMemberStatus_ShouldReturnUpdatedResponse_WhenMemberExists() {

        // Arrange
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(memberRepository.save(member)).thenReturn(member);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        MemberResponseDTO result = memberService.updateMemberStatus(1L, MemberStatus.SUSPENDED);

        // Assert — status should be updated
        assertNotNull(result);
        assertEquals(MemberStatus.SUSPENDED, member.getStatus());
    }

    @Test
    void updateMemberStatus_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.updateMemberStatus(99L, MemberStatus.INACTIVE));
    }


    // ════════════════════════════════════════════════════════════
    // assignTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void assignTrainer_ShouldReturnResponse_WhenBothMemberAndTrainerExist() {

        // Arrange
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(trainerRepository.findById(10L)).thenReturn(Optional.of(trainer));
        when(memberRepository.save(member)).thenReturn(member);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        MemberResponseDTO result = memberService.assignTrainer(1L, 10L);

        // Assert — trainer should be assigned to member
        assertNotNull(result);
        assertEquals(trainer, member.getTrainer());
    }

    @Test
    void assignTrainer_ShouldThrowNotFoundException_WhenMemberDoesNotExist() {

        // Arrange
        when(memberRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.assignTrainer(99L, 10L));
    }

    @Test
    void assignTrainer_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange — member exists but trainer does not
        when(memberRepository.findById(1L)).thenReturn(Optional.of(member));
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.assignTrainer(1L, 99L));
    }

    // ════════════════════════════════════════════════════════════
    // getMembersByTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getMembersByTrainer_ShouldReturnList_WhenTrainerExists() {

        // Arrange
        when(trainerRepository.existsById(10L)).thenReturn(true);
        when(memberRepository.findByTrainerTrainerId(10L)).thenReturn(List.of(member));
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        List<MemberResponseDTO> result = memberService.getMembersByTrainer(10L);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getMembersByTrainer_ShouldReturnEmptyList_WhenTrainerHasNoAssignedMembers() {

        // Arrange — trainer exists but has no members assigned
        when(trainerRepository.existsById(10L)).thenReturn(true);
        when(memberRepository.findByTrainerTrainerId(10L)).thenReturn(List.of());

        // Act
        List<MemberResponseDTO> result = memberService.getMembersByTrainer(10L);

        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    @Test
    void getMembersByTrainer_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.existsById(99L)).thenReturn(false);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> memberService.getMembersByTrainer(99L));
    }

}
