package com.gym.management.system.service;


import com.gym.management.system.dto.mapper.MemberDTOMapper;
import com.gym.management.system.dto.request.MemberRequestDTO;
import com.gym.management.system.dto.response.MemberResponseDTO;
import com.gym.management.system.entity.Member;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.User;
import com.gym.management.system.enums.MemberStatus;
import com.gym.management.system.enums.UserRoles;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.exception.TokenException;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.repository.TrainerRepository;
import com.gym.management.system.repository.UserRepository;
import com.gym.management.system.security.SecurityUtils;
import com.gym.management.system.service.implementationclasses.MemberServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class MemberServiceImplTest {

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private UserRepository userRepository;

    @Mock
    private MemberDTOMapper memberDtoMapper;

    @Mock
    private SecurityUtils securityUtils;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private MemberServiceImpl memberService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Member member;
    private Trainer trainer;
    private MemberRequestDTO requestDTO;
    private MemberResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Inject @Value field since Spring doesn't run in unit tests
        ReflectionTestUtils.setField(memberService, "defaultMemberPassword", "Gym@123");

        // Fake member — id is auto-generated by DB, set here just to wire up relationships
        member = new Member();
        member.setMemberId(1L);
        member.setPhoneNumber("9876543210");
        member.setMemberName("John Doe");
        member.setStatus(MemberStatus.ACTIVE);

        // Fake trainer
        trainer = new Trainer();
        trainer.setTrainerId(10L);

        // Fake request DTO — what admin sends when creating/updating a member
        requestDTO = new MemberRequestDTO();
        requestDTO.setMemberName("John Doe");
        requestDTO.setPhoneNumber("9876543210");

        // Fake response DTO returned after mapping
        responseDTO = new MemberResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // getAllMembers() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAllMembers_ShouldReturnPagedResult_WhenMembersExist() {

        // Arrange
        Page<Member> memberPage = new PageImpl<>(List.of(member));
        when(memberRepository.findAll(any(PageRequest.class))).thenReturn(memberPage);
        when(memberDtoMapper.toResponse(member)).thenReturn(responseDTO);

        // Act
        Page<MemberResponseDTO> result = memberService.getAllMembers(0, 10, "memberName", "asc");

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getTotalElements());
    }

    @Test
    void getAllMembers_ShouldReturnEmptyPage_WhenNoMembersExist() {

        // Arrange — no members in DB yet
        when(memberRepository.findAll(any(PageRequest.class))).thenReturn(Page.empty());

        // Act
        Page<MemberResponseDTO> result = memberService.getAllMembers(0, 10, "memberName", "asc");

        // Assert — empty page is valid, not an error
        assertNotNull(result);
        assertEquals(0, result.getTotalElements());
    }
}
