package com.gym.management.system.service;

import com.gym.management.system.service.implementationclasses.RefreshTokenServiceImpl;
import com.gym.management.system.entity.RefreshToken;
import com.gym.management.system.entity.User;
import com.gym.management.system.exception.TokenException;
import com.gym.management.system.repository.RefreshTokenRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class RefreshTokenServiceImplTest {

    @Mock
    private RefreshTokenRepository refreshTokenRepository;

    @InjectMocks
    private RefreshTokenServiceImpl refreshTokenService;

    // ─── Shared test data ────────────────────────────────────────────────

    private User user;
    private RefreshToken validToken;
    private RefreshToken expiredToken;

    @BeforeEach
    void setUp() {

        // Fake user — id is auto-generated by DB, set here just to wire up relationships
        user = new User();
        user.setUsername("john_doe");

        // Fake token that is still valid (expires 7 days from now)
        validToken = new RefreshToken();
        validToken.setToken("valid-token");
        validToken.setUser(user);
        validToken.setExpiryDate(Instant.now().plus(7, ChronoUnit.DAYS));

        // Fake token that has already expired (expired 1 day ago)
        expiredToken = new RefreshToken();
        expiredToken.setToken("expired-token");
        expiredToken.setUser(user);
        expiredToken.setExpiryDate(Instant.now().minus(1, ChronoUnit.DAYS));
    }

    // ════════════════════════════════════════════════════════════
    // createRefreshToken() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void createRefreshToken_ShouldReturnSavedToken_WhenCalled() {

        // Arrange — repository returns saved token
        when(refreshTokenRepository.save(any(RefreshToken.class))).thenReturn(validToken);

        // Act
        RefreshToken result = refreshTokenService.createRefreshToken(user);

        // Assert — token should be saved and returned
        assertNotNull(result);
        verify(refreshTokenRepository).save(any(RefreshToken.class));
    }

    @Test
    void createRefreshToken_ShouldSetTokenAndExpiryDate_WhenCalled() {

        // Arrange — capture what gets saved to inspect its fields
        when(refreshTokenRepository.save(any(RefreshToken.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        // Act
        RefreshToken result = refreshTokenService.createRefreshToken(user);

        // Assert — token string should not be null and expiry should be in the future
        assertNotNull(result.getToken());
        assertNotNull(result.getExpiryDate());
        assertTrue(result.getExpiryDate().isAfter(Instant.now()));
        assertEquals(user, result.getUser());
    }
}
