package com.gym.management.system.service;

import com.gym.management.system.service.implementationclasses.TrainerPaymentServiceImpl;
import com.gym.management.system.dto.mapper.TrainerPaymentDTOMapper;
import com.gym.management.system.dto.request.TrainerPaymentRequestDTO;
import com.gym.management.system.dto.response.TrainerPaymentResponseDTO;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.TrainerPayment;
import com.gym.management.system.enums.PaymentStatus;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.TrainerPaymentRepository;
import com.gym.management.system.repository.TrainerRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.*;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class TrainerPaymentServiceImplTest {


    @Mock
    private TrainerPaymentRepository trainerPaymentRepository;

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private TrainerPaymentDTOMapper trainerPaymentDTOMapper;

    @InjectMocks
    private TrainerPaymentServiceImpl trainerPaymentService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Trainer trainer;
    private TrainerPayment payment;
    private TrainerPaymentRequestDTO requestDTO;
    private TrainerPaymentResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake trainer — id is auto-generated by DB, set here just to wire up relationships
        trainer = new Trainer();
        trainer.setTrainerId(1L);
        trainer.setTrainerName("Mike");

        // Fake payment entity
        payment = new TrainerPayment();
        payment.setTrainer(trainer);
        payment.setAmount(25000.0);
        payment.setSalaryMonth("2025-01");
        payment.setStatus(PaymentStatus.PENDING);

        // Fake request DTO — what admin sends when recording a payment
        requestDTO = new TrainerPaymentRequestDTO();
        requestDTO.setTrainerId(1L);
        requestDTO.setAmount(25000.0);
        requestDTO.setSalaryMonth("2025-01");
        requestDTO.setStatus(PaymentStatus.PENDING);

        // Fake response DTO returned after mapping
        responseDTO = new TrainerPaymentResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // recordPayment() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void recordPayment_ShouldReturnResponse_WhenTrainerExistsAndNoDuplicateExists() {

        // Arrange — trainer found, no existing payment for this month
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerPaymentRepository.findByTrainerTrainerIdAndSalaryMonth(1L, "2025-01"))
                .thenReturn(Optional.empty()); // no duplicate
        when(trainerPaymentRepository.save(any(TrainerPayment.class))).thenReturn(payment);
        when(trainerPaymentDTOMapper.toResponse(payment)).thenReturn(responseDTO);

        // Act
        TrainerPaymentResponseDTO result = trainerPaymentService.recordPayment(requestDTO);

        // Assert
        assertNotNull(result);
        verify(trainerPaymentRepository).save(any(TrainerPayment.class));
    }

    @Test
    void recordPayment_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange — trainer not found in DB
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());
        requestDTO.setTrainerId(99L);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerPaymentService.recordPayment(requestDTO));

        // Verify no payment was saved
        verify(trainerPaymentRepository, never()).save(any());
    }

    @Test
    void recordPayment_ShouldThrowAlreadyPresentException_WhenPaymentForSameMonthAlreadyExists() {

        // Arrange — trainer found but payment for this month already recorded
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerPaymentRepository.findByTrainerTrainerIdAndSalaryMonth(1L, "2025-01"))
                .thenReturn(Optional.of(payment)); // duplicate found

        // Act & Assert
        assertThrows(AlreadyPresentException.class,
                () -> trainerPaymentService.recordPayment(requestDTO));

        // Verify no payment was saved
        verify(trainerPaymentRepository, never()).save(any());
    }

    // ════════════════════════════════════════════════════════════
    // getAllPayments() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAllPayments_ShouldReturnPagedResult_WhenPaymentsExist() {

        // Arrange
        Page<TrainerPayment> paymentPage = new PageImpl<>(List.of(payment));
        when(trainerPaymentRepository.findAll(any(PageRequest.class))).thenReturn(paymentPage);
        when(trainerPaymentDTOMapper.toResponse(payment)).thenReturn(responseDTO);

        // Act
        Page<TrainerPaymentResponseDTO> result =
                trainerPaymentService.getAllPayments(0, 10, "paymentDate", "asc");

        // Assert
        assertNotNull(result);
        assertEquals(1, result.getTotalElements());
    }

    @Test
    void getAllPayments_ShouldReturnEmptyPage_WhenNoPaymentsExist() {

        // Arrange
        when(trainerPaymentRepository.findAll(any(PageRequest.class))).thenReturn(Page.empty());

        // Act
        Page<TrainerPaymentResponseDTO> result =
                trainerPaymentService.getAllPayments(0, 10, "paymentDate", "asc");

        // Assert
        assertNotNull(result);
        assertEquals(0, result.getTotalElements());
    }
}
