package com.gym.management.system.service;

import com.gym.management.system.service.implementationclasses.TrainerPaymentServiceImpl;
import com.gym.management.system.dto.mapper.TrainerPaymentDTOMapper;
import com.gym.management.system.dto.request.TrainerPaymentRequestDTO;
import com.gym.management.system.dto.response.TrainerPaymentResponseDTO;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.TrainerPayment;
import com.gym.management.system.enums.PaymentStatus;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.TrainerPaymentRepository;
import com.gym.management.system.repository.TrainerRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.*;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class TrainerPaymentServiceImplTest {


    @Mock
    private TrainerPaymentRepository trainerPaymentRepository;

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private TrainerPaymentDTOMapper trainerPaymentDTOMapper;

    @InjectMocks
    private TrainerPaymentServiceImpl trainerPaymentService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Trainer trainer;
    private TrainerPayment payment;
    private TrainerPaymentRequestDTO requestDTO;
    private TrainerPaymentResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Fake trainer — id is auto-generated by DB, set here just to wire up relationships
        trainer = new Trainer();
        trainer.setTrainerId(1L);
        trainer.setTrainerName("Mike");

        // Fake payment entity
        payment = new TrainerPayment();
        payment.setTrainer(trainer);
        payment.setAmount(25000.0);
        payment.setSalaryMonth("2025-01");
        payment.setStatus(PaymentStatus.PENDING);

        // Fake request DTO — what admin sends when recording a payment
        requestDTO = new TrainerPaymentRequestDTO();
        requestDTO.setTrainerId(1L);
        requestDTO.setAmount(25000.0);
        requestDTO.setSalaryMonth("2025-01");
        requestDTO.setStatus(PaymentStatus.PENDING);

        // Fake response DTO returned after mapping
        responseDTO = new TrainerPaymentResponseDTO();
    }
}
