package com.gym.management.system.service;

import com.gym.management.system.service.implementationclasses.TrainerServiceImpl;
import com.gym.management.system.dto.mapper.MemberDTOMapper;
import com.gym.management.system.dto.mapper.TrainerDTOMapper;
import com.gym.management.system.dto.request.TrainerRequestDTO;
import com.gym.management.system.dto.response.MemberResponseDTO;
import com.gym.management.system.dto.response.TrainerResponseDTO;
import com.gym.management.system.entity.Member;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.User;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.repository.TrainerRepository;
import com.gym.management.system.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class TrainerServiceImplTest {

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private UserRepository userRepository;

    @Mock
    private TrainerDTOMapper trainerDTOMapper;

    @Mock
    private MemberDTOMapper memberDTOMapper;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private TrainerServiceImpl trainerService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Trainer trainer;
    private TrainerRequestDTO requestDTO;
    private TrainerResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Inject @Value field since Spring doesn't run in unit tests
        ReflectionTestUtils.setField(trainerService, "defaultTrainerPassword", "Trainer@123");

        // Fake trainer — id is auto-generated by DB, set here just to wire up relationships
        trainer = new Trainer();
        trainer.setTrainerId(1L);
        trainer.setTrainerName("Mike");
        trainer.setPhoneNumber("9876543210");
        trainer.setActive(true);

        // Fake request DTO — what admin sends when creating/updating a trainer
        requestDTO = new TrainerRequestDTO();
        requestDTO.setTrainerName("Mike");
        requestDTO.setPhoneNumber("9876543210");

        // Fake response DTO returned after mapping
        responseDTO = new TrainerResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // getAllTrainers() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAllTrainers_ShouldReturnList_WhenTrainersExist() {

        // Arrange
        when(trainerRepository.findAll()).thenReturn(List.of(trainer));
        when(trainerDTOMapper.toResponse(List.of(trainer))).thenReturn(List.of(responseDTO));

        // Act
        List<TrainerResponseDTO> result = trainerService.getAllTrainers();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getAllTrainers_ShouldReturnEmptyList_WhenNoTrainersExist() {

        // Arrange — no trainers in DB yet
        when(trainerRepository.findAll()).thenReturn(List.of());
        when(trainerDTOMapper.toResponse(List.of())).thenReturn(List.of());

        // Act
        List<TrainerResponseDTO> result = trainerService.getAllTrainers();

        // Assert — empty list is valid, not an error
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    // ════════════════════════════════════════════════════════════
    // getTrainerById() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getTrainerById_ShouldReturnResponse_WhenTrainerExists() {

        // Arrange
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        TrainerResponseDTO result = trainerService.getTrainerById(1L);

        // Assert
        assertNotNull(result);
    }

    @Test
    void getTrainerById_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.getTrainerById(99L));
    }

    // ════════════════════════════════════════════════════════════
    // addTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void addTrainer_ShouldReturnResponse_WhenPhoneNumberIsNotAlreadyRegistered() {

        // Arrange — phone number is unique, user and trainer created successfully
        when(trainerRepository.existsByPhoneNumber("9876543210")).thenReturn(false);
        when(passwordEncoder.encode("Trainer@123")).thenReturn("encodedPassword");
        when(userRepository.save(any(User.class))).thenReturn(new User());
        when(trainerDTOMapper.toEntity(requestDTO)).thenReturn(trainer);
        when(trainerRepository.save(any(Trainer.class))).thenReturn(trainer);
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        TrainerResponseDTO result = trainerService.addTrainer(requestDTO);

        // Assert
        assertNotNull(result);

        // Verify a user account was also created for this trainer
        verify(userRepository).save(any(User.class));
        verify(trainerRepository).save(any(Trainer.class));
    }

    @Test
    void addTrainer_ShouldSetActiveToTrue_WhenTrainerIsCreated() {

        // Arrange — trainer starts as inactive to verify service sets it to true
        trainer.setActive(false);

        when(trainerRepository.existsByPhoneNumber("9876543210")).thenReturn(false);
        when(passwordEncoder.encode("Trainer@123")).thenReturn("encodedPassword");
        when(userRepository.save(any(User.class))).thenReturn(new User());
        when(trainerDTOMapper.toEntity(requestDTO)).thenReturn(trainer);
        when(trainerRepository.save(any(Trainer.class))).thenReturn(trainer);
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        trainerService.addTrainer(requestDTO);

        // Assert — service should always set active=true on creation
        assertTrue(trainer.isActive());
    }

    @Test
    void addTrainer_ShouldThrowAlreadyPresentException_WhenPhoneNumberAlreadyRegistered() {

        // Arrange — phone number already exists in DB
        when(trainerRepository.existsByPhoneNumber("9876543210")).thenReturn(true);

        // Act & Assert
        assertThrows(AlreadyPresentException.class,
                () -> trainerService.addTrainer(requestDTO));

        // Verify no user or trainer was created
        verifyNoInteractions(userRepository);
        verify(trainerRepository, never()).save(any());
    }

    // ════════════════════════════════════════════════════════════
    // updateTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void updateTrainer_ShouldReturnUpdatedResponse_WhenTrainerExists() {

        // Arrange
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerRepository.save(trainer)).thenReturn(trainer);
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        TrainerResponseDTO result = trainerService.updateTrainer(1L, requestDTO);

        // Assert
        assertNotNull(result);
        verify(trainerRepository).save(trainer);
    }

    @Test
    void updateTrainer_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.updateTrainer(99L, requestDTO));
    }

    // ════════════════════════════════════════════════════════════
    // deleteTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void deleteTrainer_ShouldDeleteTrainerAndLinkedUser_WhenTrainerExists() {

        // Arrange — trainer has a linked user account
        User linkedUser = new User();
        trainer.setUser(linkedUser);

        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));

        // Act
        trainerService.deleteTrainer(1L);

        // Assert — both trainer and user should be deleted
        verify(userRepository).delete(linkedUser);
        verify(trainerRepository).delete(trainer);
    }

    @Test
    void deleteTrainer_ShouldDeleteTrainerOnly_WhenNoLinkedUserExists() {

        // Arrange — trainer has no linked user account
        trainer.setUser(null);
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));

        // Act
        trainerService.deleteTrainer(1L);

        // Assert — only trainer deleted, no user deletion attempted
        verify(userRepository, never()).delete(any());
        verify(trainerRepository).delete(trainer);
    }

    @Test
    void deleteTrainer_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.deleteTrainer(99L));
    }

    // ════════════════════════════════════════════════════════════
    // updateTrainerStatus() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void updateTrainerStatus_ShouldSetActiveToFalse_WhenTrainerIsDeactivated() {

        // Arrange
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerRepository.save(trainer)).thenReturn(trainer);
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        trainerService.updateTrainerStatus(1L, false);

        // Assert — trainer should now be inactive
        assertFalse(trainer.isActive());
    }

    @Test
    void updateTrainerStatus_ShouldSetActiveToTrue_WhenTrainerIsReactivated() {

        // Arrange — trainer is currently inactive
        trainer.setActive(false);
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerRepository.save(trainer)).thenReturn(trainer);
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        trainerService.updateTrainerStatus(1L, true);

        // Assert — trainer should now be active again
        assertTrue(trainer.isActive());
    }

    @Test
    void updateTrainerStatus_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.updateTrainerStatus(99L, false));
    }

    // ════════════════════════════════════════════════════════════
    // getMembersByTrainer() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getMembersByTrainer_ShouldReturnList_WhenTrainerExistsAndHasMembers() {

        // Arrange
        Member member = new Member();
        MemberResponseDTO memberResponseDTO = new MemberResponseDTO();

        when(trainerRepository.existsById(1L)).thenReturn(true);
        when(memberRepository.findByTrainerTrainerId(1L)).thenReturn(List.of(member));
        when(memberDTOMapper.toResponse(member)).thenReturn(memberResponseDTO);

        // Act
        List<MemberResponseDTO> result = trainerService.getMembersByTrainer(1L);

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getMembersByTrainer_ShouldReturnEmptyList_WhenTrainerHasNoAssignedMembers() {

        // Arrange — trainer exists but no members assigned yet
        when(trainerRepository.existsById(1L)).thenReturn(true);
        when(memberRepository.findByTrainerTrainerId(1L)).thenReturn(List.of());

        // Act
        List<MemberResponseDTO> result = trainerService.getMembersByTrainer(1L);

        // Assert — empty list is valid
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    @Test
    void getMembersByTrainer_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.existsById(99L)).thenReturn(false);

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.getMembersByTrainer(99L));
    }

    // ════════════════════════════════════════════════════════════
    // getMyProfile() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getMyProfile_ShouldReturnResponse_WhenTrainerProfileExists() {

        // Arrange — username comes from security context
        when(trainerRepository.findByUserUsername("mike_trainer")).thenReturn(Optional.of(trainer));
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        TrainerResponseDTO result = trainerService.getMyProfile("mike_trainer");

        // Assert
        assertNotNull(result);
    }

    @Test
    void getMyProfile_ShouldThrowNotFoundException_WhenNoTrainerProfileLinkedToUser() {

        // Arrange — no trainer linked to this username
        when(trainerRepository.findByUserUsername("unknown")).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.getMyProfile("unknown"));
    }
}
