package com.gym.management.system.service;

import com.gym.management.system.service.implementationclasses.TrainerServiceImpl;
import com.gym.management.system.dto.mapper.MemberDTOMapper;
import com.gym.management.system.dto.mapper.TrainerDTOMapper;
import com.gym.management.system.dto.request.TrainerRequestDTO;
import com.gym.management.system.dto.response.MemberResponseDTO;
import com.gym.management.system.dto.response.TrainerResponseDTO;
import com.gym.management.system.entity.Member;
import com.gym.management.system.entity.Trainer;
import com.gym.management.system.entity.User;
import com.gym.management.system.exception.AlreadyPresentException;
import com.gym.management.system.exception.NotFoundException;
import com.gym.management.system.repository.MemberRepository;
import com.gym.management.system.repository.TrainerRepository;
import com.gym.management.system.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class TrainerServiceImplTest {

    @Mock
    private TrainerRepository trainerRepository;

    @Mock
    private MemberRepository memberRepository;

    @Mock
    private UserRepository userRepository;

    @Mock
    private TrainerDTOMapper trainerDTOMapper;

    @Mock
    private MemberDTOMapper memberDTOMapper;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private TrainerServiceImpl trainerService;

    // ─── Shared test data ────────────────────────────────────────────────

    private Trainer trainer;
    private TrainerRequestDTO requestDTO;
    private TrainerResponseDTO responseDTO;

    @BeforeEach
    void setUp() {

        // Inject @Value field since Spring doesn't run in unit tests
        ReflectionTestUtils.setField(trainerService, "defaultTrainerPassword", "Trainer@123");

        // Fake trainer — id is auto-generated by DB, set here just to wire up relationships
        trainer = new Trainer();
        trainer.setTrainerId(1L);
        trainer.setTrainerName("Mike");
        trainer.setPhoneNumber("9876543210");
        trainer.setActive(true);

        // Fake request DTO — what admin sends when creating/updating a trainer
        requestDTO = new TrainerRequestDTO();
        requestDTO.setTrainerName("Mike");
        requestDTO.setPhoneNumber("9876543210");

        // Fake response DTO returned after mapping
        responseDTO = new TrainerResponseDTO();
    }

    // ════════════════════════════════════════════════════════════
    // getAllTrainers() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getAllTrainers_ShouldReturnList_WhenTrainersExist() {

        // Arrange
        when(trainerRepository.findAll()).thenReturn(List.of(trainer));
        when(trainerDTOMapper.toResponse(List.of(trainer))).thenReturn(List.of(responseDTO));

        // Act
        List<TrainerResponseDTO> result = trainerService.getAllTrainers();

        // Assert
        assertNotNull(result);
        assertEquals(1, result.size());
    }

    @Test
    void getAllTrainers_ShouldReturnEmptyList_WhenNoTrainersExist() {

        // Arrange — no trainers in DB yet
        when(trainerRepository.findAll()).thenReturn(List.of());
        when(trainerDTOMapper.toResponse(List.of())).thenReturn(List.of());

        // Act
        List<TrainerResponseDTO> result = trainerService.getAllTrainers();

        // Assert — empty list is valid, not an error
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    // ════════════════════════════════════════════════════════════
    // getTrainerById() tests
    // ════════════════════════════════════════════════════════════

    @Test
    void getTrainerById_ShouldReturnResponse_WhenTrainerExists() {

        // Arrange
        when(trainerRepository.findById(1L)).thenReturn(Optional.of(trainer));
        when(trainerDTOMapper.toResponse(trainer)).thenReturn(responseDTO);

        // Act
        TrainerResponseDTO result = trainerService.getTrainerById(1L);

        // Assert
        assertNotNull(result);
    }

    @Test
    void getTrainerById_ShouldThrowNotFoundException_WhenTrainerDoesNotExist() {

        // Arrange
        when(trainerRepository.findById(99L)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrows(NotFoundException.class,
                () -> trainerService.getTrainerById(99L));
    }
}
