# ===============================
# = DATABASE - PRODUCTION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# = PROD ONLY SETTINGS
# ===============================
# Don't show SQL in production
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# = SECRETS - PRODUCTION
# ===============================
jwt.secret=${JWT_SECRET}

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

default.member.password=${DEFAULT_MEMBER_PASSWORD}
default.trainer.password=${DEFAULT_TRAINER_PASSWORD}