# ===============================
# = ACTIVE PROFILE
# ===============================
spring.profiles.active=dev

# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = JWT CONFIG
# ===============================
jwt.expiration=900000