package com.gym.management.system.dto.mapper;

import com.gym.management.system.dto.request.MemberRequestDTO;
import com.gym.management.system.dto.response.MemberResponseDTO;
import com.gym.management.system.entity.Members;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for converting between Member entity and DTOs.
 *
 * MapStruct auto-generates the implementation at compile time.
 * Field names that match between entity and DTO are mapped automatically.
 * Fields that don't match or need special handling use @Mapping annotation.
 */
@Mapper(componentModel = "spring")
public interface MemberDTOMapper {

    /**
     * Converts MemberRequestDTO to Members entity.
     *
     * Fields like status, joinedDate, createdAt are ignored here
     * because they are set manually in the service, not by the client.
     */
    @Mapping(target = "memberId", ignore = true)       // auto-generated by DB
    @Mapping(target = "status", ignore = true)          // set in service as ACTIVE
    @Mapping(target = "joinedDate", ignore = true)      // set in service as today
    @Mapping(target = "createdAt", ignore = true)       // auto-set by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true)       // auto-set by @UpdateTimestamp
    @Mapping(target = "trainer", ignore = true)         // assigned separately via assignTrainer()
    @Mapping(target = "memberships", ignore = true)     // created separately via membership module
    @Mapping(target = "user", ignore = true)            // created automatically in service
    Members toEntity(MemberRequestDTO request);

    /**
     * Converts Members entity to MemberResponseDTO.
     *
     * trainer.trainerName is mapped to trainerName in the response
     * so we return just the name string instead of the full trainer object.
     */
    @Mapping(target = "trainerName", source = "trainer.trainerName") // extract just the name from trainer object
    MemberResponseDTO toResponse(Members member);
}