package com.gym.management.system.dto.mapper;

import com.gym.management.system.dto.request.MembershipPlanRequestDTO;
import com.gym.management.system.dto.response.MembershipPlanResponseDTO;
import com.gym.management.system.entity.MembershipPlan;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper for converting between MembershipPlan entity and DTOs.
 */
@Mapper(componentModel = "spring")
public interface MembershipPlanDTOMapper {

    /**
     * Converts MembershipPlanRequestDTO to MembershipPlan entity.
     * planId and active are ignored — managed by the system.
     */
    @Mapping(target = "planId", ignore = true)  // auto-generated by DB
    @Mapping(target = "active", ignore = true)   // always true on creation, toggled separately
    MembershipPlan toEntity(MembershipPlanRequestDTO dto);

    // Entity → Response DTO
    MembershipPlanResponseDTO toResponse(MembershipPlan plan);

    // List of entities → List of response DTOs
    List<MembershipPlanResponseDTO> toResponse(List<MembershipPlan> plans);
}