package com.gym.management.system.dto.mapper;

import com.gym.management.system.dto.request.TrainerRequestDTO;
import com.gym.management.system.dto.response.TrainerResponseDTO;
import com.gym.management.system.entity.Trainer;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper for converting between Trainer entity and DTOs.
 */
@Mapper(componentModel = "spring")
public interface TrainerDTOMapper {

    /**
     * Converts TrainerRequestDTO to Trainers entity.
     * Fields managed by system are ignored here.
     */
    @Mapping(target = "trainerId", ignore = true)    // auto-generated by DB
    @Mapping(target = "active", ignore = true)        // set in service as true
    @Mapping(target = "joiningDate", ignore = true)   // set in service as today
    @Mapping(target = "createdAt", ignore = true)     // auto-set by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true)     // auto-set by @UpdateTimestamp
    @Mapping(target = "user", ignore = true)          // created automatically in service
    @Mapping(target = "members", ignore = true)       // assigned separately
    Trainer toEntity(TrainerRequestDTO dto);

    // Entity → Response DTO
    TrainerResponseDTO toResponse(Trainer trainer);

    // List of entities → List of response DTOs
    List<TrainerResponseDTO> toResponse(List<Trainer> trainers);
}